spring:
  profiles:
    active: dev, test, prod
  datasource:
    url: jdbc:mysql://127.0.0.1/foro-hub
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    secret: "${JWT_SECRET:123456}"
    jwt:
      expiration: 7200000  # Tiempo de expiración de 2 horas en milisegundos
